<a href="https://colab.research.google.com/github/rjsdn0124/Practice_AI_Module/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 파이토치로 다중 로지스틱 회귀 구현하기

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

# 0.5가 넘으면 True르 반환시키고자 함.

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape)

# X가 현재 [6,2] 형태이므로 [6,1]로 만들어주기 위해 WX형태로 만들어 주려면 W는 [2,1]이 되어야 해서 해당 형태로 설정.
W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# W와 b는 현재 0으로 초기화된 상태. 이 상태에서 여러 과정을 통해 오차를 구해서 손실함수로 계산 후 기울기 재 설정 후 W,b 재설정.

# hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b))) 
# 위의 식을 torch에선 sigmoid 함수로 사용.
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)
print(y_train)

# losses = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis))
# cost = losses.mean()
# 해당 식도 함수로 구현되어있음
cost = F.binary_cross_entropy(hypothesis, y_train)

# 훈련 과정>>
optimizer = optim.SGD([W, b], lr=1)

print('='*30)
nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))
        
print(hypothesis)
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

torch.Size([6, 2])
torch.Size([6, 1])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852
tensor([[2.7711e-04],
        [3.1636e-02],
        [3.9014e-02],
        [9.5618e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
